services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/ollama
      - ./run-ollama.sh:/run-ollama.sh
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "run-ollama.sh"]
  vueapp:
    image: kand7dev99/kand7dev-projects:ollama-vue-v1
    container_name: vue-frontend
    ports:
      - 8080:8080
    depends_on:
      - ollama
volumes:
  ollama: