services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:1143
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/ollama
      - ./run-ollama.sh:/run-ollama.sh
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "run-ollama.sh"]
  vueapp:
    image: kand7dev99/kand7dev-projects:ollama-vuejs
    container_name: vue-frontend
    ports:
      - 8080:8080

volumes:
  ollama:
